name: shelf_secure_cookie
version: 1.3.0
description: >-
  Cookie parser middleware for the Shelf ecosystem.
  Reads cookies in request, sets cookies in response. 
  Supports AES-GCM for encryption if needed.
homepage: https://github.com/denisbakhtin/shelf-secure-cookie
documentation: https://github.com/denisbakhtin/shelf-secure-cookie/blob/master/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  collection: ^1.15.0
  cryptography: ^2.0.1

dev_dependencies:
  test: ^1.16.6
  shelf_router: ^1.0.0 
